(clear)
(set-sequence-operator-recognition true)
(load "DataStructure.clp")
(load "PrintAppDB.clp")
(load "general.clp")
(load "GetAppDB.clp")
(load "Specify-norm.clp")
(load "Abstract.clp")
(load "Compute.clp")
(load "Evaluate.clp")
(load "obtain.clp")
(load "match.clp")
(load "Messages.clp")
(load "ui.clp")
(run)
